### ISSUE TITLE
OCBC CSV TRIGGER MAIL

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PHP-CRM#11]
@safiyullahmohideen 

1.Today two mails received from CSV Trigger Database updated .   . Forwarded the mail .
2. CR : Change subject for this mail as: OCBC RECORDS --[07-03-2016,08-03-2016,09-03-2016] instead of 'DATABASE UPDATED-[07-03-2016,08-03-2016,09-03-2016]

**Comment by DHANDAPANISATTANATHAN** [comment]
@safiyullahmohideen 

# FIX THIS.

# OCBC TO , OCBC CC. = HTML RECORD UPDATED MAIL ONLY

# OCBC CONFIRM =  SINGLE LINE DATE INSERTED & NO CSV RECORD FOUND.

**Comment by safiyullahmohideen** [comment]
status:closed
