### ISSUE TITLE
DEPOSIT DED. FOR OLD CUSTOMERS DEPOSIT NOT APPEARING 

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PHP-CRM#13]
@DHANDAPANISATTANATHAN 

#2318 Oswald , #1915 MT marine 

Deposit not show up in DD sheet . Plz chk

**Comment by DHANDAPANISATTANATHAN** [comment]
In customer table didnt have DEPOSIT, So this one not come in DD .
if You want update that customer in CC update and extract !
