### ISSUE TITLE
EI DEF ON 23022016

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/EI-PHP-CRM#14]
@safiyullahmohideen 

1.Why OS address not come in Contract and Invoice?
2.Customer UAT - Shld load email address entered in EMAIL profile under CUSTOMER UAT.
But Email Profile under Customer loading

CR:
3.Restrict in Email profile entry in To, CC, BCC dont allow to enter duplicate.

**Comment by safiyullahmohideen** [comment]
1.In Contract Unit address loaded  script corrected.
2.query changed in customer uat to load email address.
3.Already duplicate not allowed via form in email profile entry

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: to_be_tested

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: Defect

Fix the below and re deliver quickly

![def_25032016](https://cloud.githubusercontent.com/assets/9882142/14041172/657a3874-f294-11e5-8f58-611cc9dc5f30.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
# CR

Implement UNIT address get from db and Load using T1,T2 & OS validation in invoice also

Refer the below image

![ei_253_1](https://cloud.githubusercontent.com/assets/9882142/14041479/49ddf3d2-f297-11e5-9792-2da8005d5e76.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
@safiyullahmohideen 

You shld fix quickly and deliver.also shld reduce defect. Planned to prod sterday, But issue found.

Today OS, DD PDF SHLD GO TO PROD.

**Comment by safiyullahmohideen** [comment]
DD PDF working for me correctly , then how can i check... [need to analysis ]. Becuase i didn't change any script.. what script in EI DD extraction, same script only i used.

OS address yesterday evening only assigned .. that one finished , now testing..

**Comment by DHANDAPANISATTANATHAN** [comment]
@ Safi,

I tested in your DD SS only, I didnt change anything,What issue/ why coming/ You shld chek and tell,

My question is Why you didnt get this error? How you missed. You shld test more scenario? Dont test with two or three Customer. you shld check more that 10 rec ver customer.then only you will know.


All shld go to prod today. If  not tmrw for sure. You decide!

**Comment by DHANDAPANISATTANATHAN** [comment]
# CR

Report -----> UNIT-----> Login and Star Hub details

Show only active unit 

Shld go to prod today

**Comment by safiyullahmohideen** [comment]
updated script to load only active units only

**Comment by safiyullahmohideen** [comment]
status:closed
