### ISSUE TITLE
EI ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/EI-PHP-CRM#3]
SL,

AFTER ADDING CUSTOMER AND PAYMENT RESTRICTION. I TRY TO CREATE CUSTOMER.

BUT CALENDAR NOT CREATED. I THOUGHT SOME SA ISSUE IN UAT.

BUT I TRIED THE SAME SCRIPT IN INT. HERE ALSO I CANNT CREATE CUSTOMER.

CHECK AND TELL ME. WHICH SCRIPT HAVE ISSUE. MAY DID U GIVE ANY EXTRA SCRIPT TOME

**Comment by DHANDAPANISATTANATHAN** [comment]
CHECK AND CLOSE THE false msg in EXTRCTION!

**Comment by SaradambalMunusamy** [comment]
Regarding calendar issue,
Due to missing EI-PHP-INT-6088b372ef98.p12 got issue in int

Regarding extraction,

Sometime success returning empty ,But successfully extracting without log error. 
Shall i show success msg if it is empty also?

**Comment by DHANDAPANISATTANATHAN** [comment]
@SaradambalMunusamy 


In payment Extraction.

Some scenario Payment amt and deposit row value font color changed to white.

Most priority Close it!

**Comment by DHANDAPANISATTANATHAN** [comment]
@SaradambalMunusamy 

Fix this also

https://github.com/SSOMENSREPO/EI-PATCH/issues/22

**Comment by DHANDAPANISATTANATHAN** [comment]
@SaradambalMunusamy 

# Why delay??????

I need immediately. Fix and give me Cannt wait!

**Comment by SaradambalMunusamy** [comment]
sir, this one already having issue. i need to check each and every line of script of gas script.

Cant do immediately.

**Comment by DHANDAPANISATTANATHAN** [comment]
Fix PAYMENT EXTRACTION AND OTHER ISSUE TODAY!

**Comment by SaradambalMunusamy** [comment]
closed and delivered in https://github.com/SSOMENSREPO/EI-PHP-CRM/releases/tag/v0.7

**Comment by DHANDAPANISATTANATHAN** [comment]
Tested and closed

**Comment by DHANDAPANISATTANATHAN** [comment]
@SaradambalMunusamy 

# Active cc list sorting shld be UNIT,CUSTNAME AND LP wise. But You removed unit wise sorting in first sheet.

# fix and dely

**Comment by DHANDAPANISATTANATHAN** [comment]
# STATUS: FIXED

Fixed
